### ISSUE TITLE
failing on npm start (Linux x64)

### ISSUE THREAD

**Issue by mackenza** [zaggino/brackets-electron#1]
@zaggino where does it get the `electron` executable from when you do a `electron ./app/index.js`?

Do make it run, I did the following:
1. `./node_modules/electron-prebuilt/install.js` which created a `dist` folder with an `electron` executable
1. edited `package.json` start script to do `./node_modules/electron-prebuilt/dist/electron ./app/index.js`
1. `npm start`

I get an Electron shell window but there is no Brackets stuff in it. I don't think I have done the right things to make this work.

Perhaps I should just try on Windows and leave Linux for later?

**Comment by mackenza** [comment]
I do see a console error message that could be a show stopper, I guess:

`[21368:0503/062005:INFO:CONSOLE(125)] "Uncaught Error: getApplicationSupportDirectory() not implemented for platform linux", source: /home/mackenza/projects/brackets-electron/app/appshell/app.js (125)`

I will look into that.

**Comment by zaggino** [comment]
I have worked just on Windows today so that one works. You can put electron to your path by using `sudo npm install -g electron-prebuilt` but I didn't have to do that on Windows and neither I needed to do that `./node_modules/electron-prebuilt/dist/electron ./app/index.js` step you mentioned. It might take a bit of effor to make all three platforms running.

we're using https://github.com/mafintosh/electron-prebuilt because I didn't want to spend time building electron from scratch

**Comment by mackenza** [comment]
ok... I wonder if we should work on 1 platform till it's solid then others or should we work on all 3 in parallel?

I believe it's failing because of the way we are currently retrieving the APPDATA stuff which is Windows-specific.

**Comment by zaggino** [comment]
There shouldn't be much platform specific stuff. I'll fix the mac tomorrow at work but I don't have linux vm at hand right now so that one will come a bit later.

**Comment by mackenza** [comment]
I will take a stab at fixing Linux

**Comment by zaggino** [comment]
Ok, to see what the expected result should be, just open developer tools in normal Brackets and execute `brackets.app.getApplicationSupportDirectory()`

**Comment by mackenza** [comment]
fixed... will submit PR soon

**Comment by mackenza** [comment]
hmm... not sure how to submit a PR for this. If I fork the repo, it gives me a fork of adobe/brackets which I already have. How do I submit it to this repo, not Brackets?

**Comment by zaggino** [comment]
dunno right now, I've made you a collaborator, just clone this repo and push a branch to it (never to master please)

**Comment by mackenza** [comment]
until we figure that out, here is the code:

``` javascript
} else if (process.platform === "linux") {
        return path.resolve("/home/", process.env.USER, ".config/Brackets");
```

**Comment by zaggino** [comment]
but googling -> http://faisonz.com/blog/send-pull-request-to-another-github-fork/

**Comment by zaggino** [comment]
_I've also made @MarcelGerber a collaborator in case he wanted to spare some time with this. (based on brackets-dev emails)_
