### ISSUE TITLE
Error on updating extension

### ISSUE THREAD

**Issue by p4bl1t0** [zaggino/brackets-electron#10]
When I want to update the brackets extension from the extension manager I am getting the following error: 
![brackets error on download extension](https://cloud.githubusercontent.com/assets/886512/7466440/5157371a-f2b9-11e4-9efc-e3c48a9ae747.png)

**Comment by zaggino** [comment]
What windows do you have?

**Comment by p4bl1t0** [comment]
It's not Windows, it's Deepin Linux (Ubuntu Trusty based distribution).

**Comment by zaggino** [comment]
I don't have Linux but maybe @mackenza can help here.

**Comment by mackenza** [comment]
@p4bl1t0 what extension were you updating?

**Comment by p4bl1t0** [comment]
Brackets-Git

**Comment by mackenza** [comment]
it's actually worse than that. I cannot install an extension on Linux either. I think it has to do with the temp folder the zip file is being downloaded to. I am looking into this.

**Comment by mackenza** [comment]
should be addressed by #14

**Comment by zaggino** [comment]
@p4bl1t0 can you test this again and confirm/close?

**Comment by p4bl1t0** [comment]
It's working properly. Things that I tested:
- Update an extension
- Add a new extension
- Delete one extension

The changes preserve also after closing and reopening Brackets
