### ISSUE TITLE
Can't run AppImage

### ISSUE THREAD

**Issue by anonimo82** [zaggino/brackets-electron#104]
### Prerequisites

* [x] Is this `Brackets-Electron` specific problem (did you test it with latest [brackets build](http://brackets.io/))?
I didn't try with the official release, because I just need the AppImage
### Description

[Description of the bug or feature]
As I try to run the AppImage, any version provided, I get an error similar to this one:
```
installed: X-AppImage-BuildId=9a269020-4268-11a7-24ad-052b996347de image: X-AppImage-BuildId=9a269020-4268-11a7-24ad-052b996347de
Segmentation fault (core dumped)
```

### Versions

[Please include the OS and what version of `Brackets-Electron` you're running.]
Xubuntu 22.04 and Brackets Electtron 1.10.3 x64

**Expected behavior:** [What you expected to happen]
The editor should open

**Actual behavior:** [What actually happened]
Error (see above)

**Comment by anonimo82** [comment]
P.S.: I also tried the .deb, just got a segmentation fault

**Comment by anonimo82** [comment]
Anyone?

**Comment by petetnt** [comment]
Hey @anonimo82,

sadly the Brackets project has been ended and there's a very small chance that someone sees this and/or is able to help 😞 I saw the messages by chance but I don't know anything about the Electron fork myself.

If you are looking for an open source editor, VSCode seems to have an up-to-date AppImage https://apprepo.de/appimage/vscode

**Comment by anonimo82** [comment]
Ok, I'd prefer Brackets, but I'm ok with Code too.
Thanks a lot!
