### ISSUE TITLE
sort out how extensions use app.getUserDocumentsDirectory

### ISSUE THREAD

**Issue by zaggino** [zaggino/brackets-electron#19]

**Comment by marcelgerber** [comment]
I did a GitHub search for such function calls: https://github.com/search?l=javascript&q=app+getUserDocumentsDirectory+brackets&ref=searchresults&type=Code&utf8=%E2%9C%93

Tomorrow, I could give you more detailed and complete results frommsearching my whole downloaded repository.

**Comment by mackenza** [comment]
It looks like it's just a starting point for file browsing. I doubt any of those extensions would actually "break" if we made it just go to `getPath("home")` or another reasonable default.

My vote is to get Brackets to deprecate it and implement it in Bracketron with some sort of x-platform default that works. It's not a useful API for a code editor to look for a Documents folder imo.

**Comment by mackenza** [comment]
any idea how the brackets-shell native code handles resolution of the localized Documents path?

**Comment by zaggino** [comment]
for now https://github.com/zaggino/brackets-electron/commit/0187595d38f9ef5d20d9f3d2ed2eac34bf27e75f

we can discuss here if we're able to implement `app.getUserDocumentsDirectory` with a reasonable amount of effort

**Comment by mackenza** [comment]
I like the approach there... (I guess I suggested it so why not like it lol)

**Comment by ingorichter** [comment]
This is how brackets-shell is handling it
https://github.com/adobe/brackets-shell/blob/master/appshell/client_app_mac.mm#L94
