### ISSUE TITLE
mac: invalid name in the top-left corner of the screen

### ISSUE THREAD

**Issue by zaggino** [zaggino/brackets-electron#23]
![image](https://cloud.githubusercontent.com/assets/1067319/7531891/7aece808-f5a3-11e4-8124-759ab8405fe3.png)

**Comment by ingorichter** [comment]
we need a `post-install` script in our package.json or we update the name before the installer is created. The name is in Electrons Info.plist file and cannot be set programmatically.

**Comment by marcelgerber** [comment]
I think we need to build Electron ourselves (with a custom config) in order to fix this bug.

**Comment by zaggino** [comment]
Do you think we should try to take advantage of https://github.com/maxogden/electron-packager or just go straight for https://github.com/paulcbetts/grunt-build-atom-shell ?

**Comment by sbruchmann** [comment]
Hello @zaggino,

[Citing electron-docs](https://github.com/atom/electron/blob/master/docs/api/menu.md#main-menus-name):

> On OS X the label of application menu's first item is always your app's name, no matter what label you set. To change it you have to change your app's name by modifying your app bundle's Info.plist file. See About Information Property List Files for more.

Hope that helps.
