### ISSUE TITLE
Low quality title bar and tray icons on Windows

### ISSUE THREAD

**Issue by marcelgerber** [zaggino/brackets-electron#27]
On Windows, both the title bar icon and the tray icon are of way worse quality than they are in Brackets core.

See https://github.com/atom/atom/issues/4811 for info how they fixed that.

Title bar icon:
![image](https://cloud.githubusercontent.com/assets/2641501/7549469/f96e9914-f635-11e4-824c-76e8eed5ff7d.png)

Tray icon:
![image](https://cloud.githubusercontent.com/assets/2641501/7549471/23068c32-f636-11e4-8c0c-b7ef06657b79.png)

**Comment by zaggino** [comment]
This should be fixed in current master.

**Comment by zaggino** [comment]
Icons in https://github.com/zaggino/brackets-electron/tree/master/build/icons are used right now, closing.
