### ISSUE TITLE
Running unit tests destroys all menus and menu items

### ISSUE THREAD

**Issue by ingorichter** [zaggino/brackets-electron#35]
It seems, that the unit tests are removing all menus and menu items during the test run

**Comment by zaggino** [comment]
Yes, unit tests for native menus do that, I'm not 100% sure why yet, but I think that the menu entries in `Electron` are shared between windows, but in `brackets-shell` they're `per window`

**Comment by ingorichter** [comment]
Yes, I think that's the case. :-/

**Comment by zaggino** [comment]
Nothing that's not fixable ;)
