### ISSUE TITLE
Change App Support directory to "Brackets-Electron" for development?

### ISSUE THREAD

**Issue by marcelgerber** [zaggino/brackets-electron#4]
Would it make sense to use another AppData folder for brackets-electron so it cannot fuck up the existing Brackets installation (only for development, of course)?

The change would be easy... Just change https://github.com/zaggino/brackets-electron/blob/b47cc9d5e65617d2c1cd4fe7842708dcf522831c/app/appshell/app.js#L123-L131

**Comment by zaggino** [comment]
:+1:

**Comment by mackenza** [comment]
I was thinking the same thing... nice work Marcel
