### ISSUE TITLE
grunt task to create distributable for linux

### ISSUE THREAD

**Issue by zaggino** [zaggino/brackets-electron#40]

**Comment by zaggino** [comment]
@MarcelGerber if you could have a look, now that https://github.com/zaggino/brackets-electron/issues/38 is done, it shouldn't require much code

**Comment by marcelgerber** [comment]
We only need to add an `author.email` field to our `package.json`, then we're all good here.

**Comment by zaggino** [comment]
any idea what that email should be?

**Comment by marcelgerber** [comment]
Just looked it up, `brackets-shell` uses brackets-dev@googlegroups.com (https://github.com/adobe/brackets-shell/blob/da088ef847ad3efce726a24be087bd7b92e9a77f/installer/linux/debian/control#L9).

Not sure if we can use an official email here, though...

**Comment by zaggino** [comment]
I think we can, that group is a public one, not private: https://groups.google.com/forum/#!forum/brackets-dev
