### ISSUE TITLE
native menus on Linux

### ISSUE THREAD

**Issue by mackenza** [zaggino/brackets-electron#5]
I am trying to figure out where Brackets determines Linux cannot handle native menus. I have traced some stuff in `utils/Global.js` but I cannot find where it determines this.

**Comment by zaggino** [comment]
try

```
var indexPath = "file://" + path.resolve(__dirname, "..", "src", "index.html") + "#hasNativeMenus=true";
```

in app/index.js

**Comment by mackenza** [comment]
didn't work.

**Comment by mackenza** [comment]
I changed it to `"?hasNativeMenus=true"` and it worked.

Is this the actual way to do it, though? The Windows version doesn't use that switch, does it?

Anyway, closing this for now. We can pursue a different fix later, I suppose.

**Comment by marcelgerber** [comment]
Yeah, we should look into the variables normally set by Brackets-Shell. I'll do that tomorrow (hopefully).

**Comment by zaggino** [comment]
leave it open until it's fixed ;)
