### ISSUE TITLE
how/where would you load node modules in extension code?

### ISSUE THREAD

**Issue by mackenza** [zaggino/brackets-electron#56]
``` javascript
const fs = require('fs');

define(function (require, exports, module) {
    "use strict";

    var CommandManager = brackets.getModule("command/CommandManager"),
        EditorManager  = brackets.getModule("editor/EditorManager"),
        Menus          = brackets.getModule("command/Menus");

    var theText = fs.readFileSync('hello-world.txt');

    // Function to run when the menu item is clicked
    function handleHelloWorld() {
        var editor = EditorManager.getFocusedEditor();
        if (editor) {
            var insertionPos = editor.getCursorPos();
            editor.document.replaceRange(theText, insertionPos);
        }
    }


    // First, register a command - a UI-less object associating an id to a handler
    var MY_COMMAND_ID = "helloworld.writehello";   // package-style naming to avoid collisions
    CommandManager.register("Hello World 2", MY_COMMAND_ID, handleHelloWorld);

    // Then create a menu item bound to the command
    // The label of the menu item is the name we gave the command (see above)
    var menu = Menus.getMenu(Menus.AppMenuBar.FILE_MENU);
    menu.addMenuItem(MY_COMMAND_ID);
});
```

So that totally fails. 

So where should I be loading my NodeJS modules?
Won't the NodeJS `require` conflict with the RequireJS `require`.

Am I missing something obvious?

**Comment by zaggino** [comment]
```
const fs = node.require('fs');
```

should do the trick

**Comment by mackenza** [comment]
nope. I tried it above and inside the define() and I get a bunch of errors that it can't load menus and other Brackets modules.

**Comment by mackenza** [comment]
node looks to be a global. I get hints on it when I go to type it.

**Comment by zaggino** [comment]
This seems to work fine:
https://github.com/zaggino/brackets-electron/blob/master/src/filesystem/impls/appshell/AppshellFileSystem.js#L124

**Comment by mackenza** [comment]
maybe because I am in an extension?

I will play with it some more I guess.

**Comment by mackenza** [comment]
ok it was something else. There were 147 errors and I was missing a file that caused the rest of the extension not to load.

**Comment by mackenza** [comment]
I spoke too soon. The extension loads now but it doesn't actually work and I get 142 errors now.

**Comment by zaggino** [comment]
If you link the extension repo here, I can look at it later (when more important stuff is resolved).
Unless you want to put up a PR with fix :-)

**Comment by ingorichter** [comment]
@mackenza where is your repo?

**Comment by mackenza** [comment]
https://github.com/mackenza/behw
I recreated it and can't test just now, but last time I tried this, it gave me all kinds of errors about loading modules.

**Comment by zaggino** [comment]
@mackenza see https://github.com/mackenza/behw/pull/1/files
