### ISSUE TITLE
refactor out RequireJS?

### ISSUE THREAD

**Issue by mackenza** [zaggino/brackets-electron#60]
Electron allows us to use the Node module loader in both main and renderer processes. Would it make sense to refactor the module loading to remove requirejs altogether? It seems to me to be redundant now.

**Comment by zaggino** [comment]
@mackenza that'd require doing a full-out fork, I wouldn't be able to merge master from https://github.com/adobe/brackets anymore.

**Comment by mackenza** [comment]
I see. I guess that requires a commitment beyond what this project can do, right?

**Comment by zaggino** [comment]
Definitely. And unless this is stable (releasable) I would not put any effort into it. One step at a time.

**Comment by mackenza** [comment]
I am not known for my patience ;)

Closing as "a boy can dream, can't he?" :8ball:
