### ISSUE TITLE
AppImage creates .desktop file which puts it in "Other" menu rather than "Development"

### ISSUE THREAD

**Issue by mackenza** [zaggino/brackets-electron#65]
### Description

Now that we are producing AppImages and not debs, there are some finer points to work out. One of them is this minor issue where the .desktop file doesn't adequately categorize the app.
### Versions

Linux 1.8.2
### Steps to Reproduce
1. Install the AppImage
2. Go to your menu (for whatever desktop you are using)
3. Observe that the launcher for Brackets Electron is in "other".

**Expected behavior:** it probably should be in something like "Development" as VSCode is.

**Comment by mackenza** [comment]
This may be an Electron-Packager issue as I don't see any config that allows you to choose the category in their docs.

**Comment by zaggino** [comment]
@mackenza The category is set here: https://github.com/zaggino/brackets-electron/blob/master/package.json#L23 but I think that's Mac only.

**Comment by mackenza** [comment]
yes, that is why I think it's a limitation of Electron-Packager

**Comment by probonopd** [comment]
Inside the AppImage (which is an ISO file, so you can loop-mount it to inspect), you will find a `$APPNAME.desktop` file which needs to be edited to contain the correct `Categories=` entry.

**Comment by zaggino** [comment]
Open a new issue in the electron-builder, until thst is fixed, not much to do here ;-)

**Comment by mackenza** [comment]
I would like to keep this open as it will take some changes here when/if it gets covered in electron-builder.

**Comment by probonopd** [comment]
Feature added in electron-builder https://github.com/electron-userland/electron-builder/issues/504#issuecomment-245378819 thanks @develar

**Comment by mackenza** [comment]
I am going to assume this work by @develar is going to satisfy this issue and am closing it. I will try it out once it gets into a release.

**Comment by probonopd** [comment]
Well, the category needs to be defined in `package.json` as explained in https://github.com/electron-userland/electron-builder/wiki/Options#LinuxBuildOptions-category. So some work needs to be done in brackets-electron as well @mackenza.

**Comment by zaggino** [comment]
@mackenza @probonopd see https://github.com/zaggino/brackets-electron/commit/632ced2c771d9f2c8a54338269a76b965ed400bf, not sure what should the settings of `desktop` be so feel free to open a PR

**Comment by mackenza** [comment]
@zaggino here is what VSCode has... I think it looks about right.

`Utility;TextEditor;Development;IDE;`

so...

``` javascript
"linux": {
     "category": "Utility;TextEditor;Development;IDE;"
 }
```

I would PR this but am not near a dev machine atm

**Comment by zaggino** [comment]
@mackenza please check AppImage in https://github.com/zaggino/brackets-electron/releases/tag/v1.8.2 if this is fixed

**Comment by mackenza** [comment]
fix confirmed... closing
