### ISSUE TITLE
Fix getApplicationSupportDirectory() on darwin

### ISSUE THREAD

**Issue by sbruchmann** [zaggino/brackets-electron#7]
Hello @zaggino,

as I’ve already forked the brackets repository in the past, I am not able to fork this repository as well and therefore I am unable to send a pull request for this rather small change:

Replace [app/appshell/app.js#L130](https://github.com/zaggino/brackets-electron/blob/e2ffa73dd66bd016021cb658db4ccc0d2e7f83ef/app/appshell/app.js#L130) with this:

``` javascript
return path.resolve("/", "Users", process.env.USER, "Application Support", folderName);
```

**Comment by zaggino** [comment]
Hi, in case you wanted to submit a PR, try this in your brackets fork:

```
git remote add brackets-electron https://github.com/zaggino/brackets-electron.git
git fetch brackets-electron
git checkout -b electron/feature --track brackets-electron/master
...work...
git push
```

http://faisonz.com/blog/send-pull-request-to-another-github-fork/
