### ISSUE TITLE
Project contributing guidelines thoughts

### ISSUE THREAD

**Issue by mackenza** [zaggino/brackets-electron#75]
I listened to a very good podcast today with Rod Vagg from NodeSource/NodeJS fame. It was the [Request for Commits](https://changelog.com/rfc-7/) podcast and Rod was discussing the Liberal Contribution governance model in place in a project he started called LevelUp (a node wrapper for LevelDB). Here is their [contributing.md](https://github.com/Level/community/blob/master/CONTRIBUTING.md)

I think this would be a great model for how this fork is run. It basically relies on trust and that "ownership" of a project should be for anyone that provides a "significant contribution" to it. Exactly the opposite of a BDFL or corporate-controlled model.

Also check out Mikael Rogers (also of NodeJS fame) talking about growing your contributor base (where he also references Rod Vagg's LevelUp project) here: https://opensource.com/life/16/5/growing-contributor-base-modern-open-source

And finally, I think removal of the [Brackets Contributor License Agreement](http://dev.brackets.io/brackets-contributor-license-agreement.html) is a must.

**Comment by zaggino** [comment]
Can't say I disagree with anything in the doc, haven't heard the podcast yet, maybe I will give it a go. So far this fork is run only as an alternative shell to Brackets - adding **major** features not present there is highly unlikely at this point in time.

Anybody is welcome to contribute to anything they might think would be useful, taking in mind that this forks aims to preserve compatibility with Brackets master repository and its extensions, so no breaking changes are acceptable for the time being.

Above might change in the future if there's interest and demand for it.

Brackets CLA is ignored by this fork, nobody cares.
