### ISSUE TITLE
Duplicate line (Ctrl+D) won't work. Deleting line instead

### ISSUE THREAD

**Issue by AgamlaRage** [zaggino/brackets-electron#79]
### Description

The shortcut "Ctrl+D" to copy-paste current line or selection won't work.
It's deleting the current line instead.

### Config 
I use **Brackets 1.8** ,and **Brackets-Electron 1.8.4** (made update today).
Windows 10 (1607).

Bug appear only in Brackets-Electron.

### Steps to Reproduce

1. Open a text file (I tried, js, css, scss, php)
2. Choose a line, and put your cursor into it (start, end or anywhere inside)
3. press **Ctrl+D**

**Expected behavior:** In Brackets, this shortcut will copy-paste the current line just below.

**Actual behavior:** The line is deleted

**Comment by ghost** [comment]
This applies to more keyboad shortcuts, for example "Move Line Up" and "Move Line Down" and remapping didn't work for me as well. In this state it's quite unusable for me.

**Comment by zaggino** [comment]
Fixed now on master, I'll release 1.9.1 shortly after fixing some build issues.

**Comment by zaggino** [comment]
@AgamlaRage @mskocik fixed in https://github.com/zaggino/brackets-electron/releases/tag/v1.9.1
