### ISSUE TITLE
White screen after the build, codemirror.js error

### ISSUE THREAD

**Issue by apla** [zaggino/brackets-electron#82]
### Prerequisites

* [x] Is this `Brackets-Electron` specific problem (did you test it with latest [brackets build](http://brackets.io/))?

### Description

CodeMirror need to be rolled up before starting app. Without this, `dist/www/thirdparty/CodeMirror/lib/codemirror.js` is not found.

### Versions

master, 1.9.1

**Comment by zaggino** [comment]
👍 this is something that's currently being discussed in original brackets repository so I didn't take any action here yet

**Comment by zaggino** [comment]
@apla this is now fixed in master
