### ISSUE TITLE
Wakatime extension error

### ISSUE THREAD

**Issue by ghost** [zaggino/brackets-electron#85]
### Prerequisites

* [x] Is this `Brackets-Electron` specific problem (did you test it with latest [brackets build](http://brackets.io/))?

### Description

On first launch after Wakatime install, Wakatime prompts for wakatime API key. In console it throwss this error message `C:/Users/Martin/AppData/Roaming/Brackets-Electron/extensions/user/brackets-wakatime - Error: prompt() is and will not be supported.`

### Versions

1.8 Win7 64bit

### Steps to Reproduce

1. Install wakatime extension
2. Restart Brackets-Electron
3. No Wakatime key prompt

**Expected behavior:** Prompt or other possibility to enter wakatime key

**Actual behavior:** extension error

**Comment by zaggino** [comment]
https://github.com/electron/electron/issues/472

**Comment by ghost** [comment]
Closed by wakatime/brackets-wakatime#4
