### ISSUE TITLE
Extension with native code

### ISSUE THREAD

**Issue by ficristo** [zaggino/brackets-electron#89]
### Prerequisites

* [x] Is this `Brackets-Electron` specific problem (did you test it with latest [brackets build](http://brackets.io/))?

### Description

I tryed to install [my extension](https://github.com/ficristo/brackets-terminal-x) manually but it fails with this message in the console:
```
failed to run terminals.startConnection:  Unable to load one of the modules: ...../AppData/Roaming/Brackets-Electron/extensions/user/brackets-terminal-x/src/node/TerminalsDomain, reason: Error: A dynamic link library (DLL) initialization routine failed.
\\?\.....\AppData\Roaming\Brackets-Electron\extensions\user\brackets-terminal-x\node_modules\node-pty\build\Release\pty.node
```
do you have an idea?

I tryed to delete the `.npmrc`  file or to add one like this but failed.
```properties
# Electron's version.
npm_config_target=1.6.2
# The architecture of Electron, can be ia32 or x64.
npm_config_arch=x64
npm_config_target_arch=x64
# Download headers for Electron.
npm_config_disturl=https://atom.io/download/electron
# Tell node-pre-gyp that we are building for Electron.
npm_config_runtime=electron
# Tell node-pre-gyp to build module from source code.
npm_config_build_from_source=true
```

### Versions

Windows 10
1.9.4

### Steps to Reproduce

1. Clone https://github.com/ficristo/brackets-terminal-x/releases in the extensions folder
2. Delete the `.npmrc` file
2. Run npm install (with the same node version of Brackets-Electron)
3. Start Brackets

**Expected behavior:** [What you expected to happen]
My extensions should load

**Actual behavior:** [What actually happened]
An error is logged on the console

**Comment by ingorichter** [comment]
The path in the console log looks broken to me. Wondering who can't deal with windows paths properly
