### ISSUE TITLE
Shortcuts edit.moveDown & edit.moveUp not working

### ISSUE THREAD

**Issue by mskocik** [zaggino/brackets-electron#91]
### Prerequisites

* [x] Is this `Brackets-Electron` specific problem (did you test it with latest [brackets build](http://brackets.io/))?

### Description

Shortcuts for moving line up `Ctrl-Shift-Up` and down `Ctrl-Shift-Down` don't work. Cannot be redefined.

### Versions

Linux Mint 18
Release 1.10 experimental build 1.10.2 (master f3e00c082) 
build timestamp: Mon May 08 2017 01:26:20 GMT+0000

### Steps to Reproduce

1. Place cursor un editor
2. Press `Ctrl-Shift-Up`

**Expected behavior:** Line move above

**Actual behavior:** selection spread to line above

**Comment by zaggino** [comment]
@mskocik released `1.10.3`
