### ISSUE TITLE
A build of master doesn't run correctly

### ISSUE THREAD

**Issue by ficristo** [zaggino/brackets-electron#94]
### Prerequisites

* [x] Is this `Brackets-Electron` specific problem (did you test it with latest [brackets build](http://brackets.io/))?

### Description

After a clean install codemirror is not available

### Versions

Windows
master rev 3c44e8259c4e134aa2a0905cf9347544b9900aca

### Steps to Reproduce

1. git clean -xdf 
2. npm install
3. npm run dev
4. npm start -- --enable-logging

**Expected behavior:** [What you expected to happen]
CodeMirror should be available

**Actual behavior:** [What actually happened]
CodeMirror is not available

**Comment by zaggino** [comment]
Due to changes in CodeMirror build it's no longer possible to link directly to Github commit. Fixed.
